import streamlit as st
from joblib import load
import pickle
st.set_page_config(
    page_title="Large Language Models (LLMs) Generated Text Detection",
    page_icon="🔎",
)
st.title("Large Language Models (LLMs) Generated Text Detection")
st.write("<div style='color: #3366ff;font-size: 20px;font-weight: bold;'> Detect ChatGPT3, GPT3.5 and Gemini in seconds</div>",unsafe_allow_html=True)
st.write("---")
#st.write("#")

# Loading the model
#loaded_pipeline = load('train_model.joblib')
loaded_pipeline=load("LLMs_model.pkl")
# Prediction Func
def aigenerate(text: list) -> str:
    predictions = loaded_pipeline.predict(text)
    if predictions == 1:
        return 'Generated by AI'
    if predictions == 0:
        return 'Generated by Humans'

#App code
placeholder_message = "Send a message"
if "my_input" not in st.session_state:
    st.session_state["my_input"] = ""
my_input = st.text_input("Input Text Here",st.session_state["my_input"], placeholder=placeholder_message)
submit = st.button("Analyze Text")

if submit:
    if not my_input:  # if input text is empty
        st.error("Please enter text into the textbox.")
    else:
        st.session_state["my_input"] = my_input
        
        prediction = aigenerate([my_input])
        st.success(prediction)