import streamlit as st
import pandas as pd
import altair as alt

st.markdown("<span style='color: #3366ff; font-weight: bold;font-size: 35px'>About Large Language Models(LLMs Detector)</span>", unsafe_allow_html=True)

st.write("""
<div  style='font-family: "Times New Roman", Times, serif; font-size: 18px; color: #ffff;text-align: justify;'>
An LLMs detector refers to tools and methods used to identify text that has been generated by large language models (LLMs). 
These detectors are designed to distinguish between human-written content and content produced by AI models, which is becoming 
increasingly important as LLMs become more advanced and widespread. 
The development of LLMs detectors is a response to the potential misuse of AI-generated text,
such as spreading misinformation or committing academic fraud. </div>  """, unsafe_allow_html=True)
st.write("##")
st.write("""   
<div style='font-family: "Times New Roman", Times, serif; font-size: 18px; color: #ffff;text-align: justify;'>
An LLMs Detector confidently detects texts generated by the most popular tools, like ChatGPT, Gemini, and Copilot.
GPT2, GPT3, and GPT3.5 are detected with high accuracy, while the detection of GPT4 is supported on an experimental basis.
Note that no AI Detector can provide complete accuracy. As language models continue to develop, detection tools will always have to race to keep up with them.</div> """, unsafe_allow_html=True)

st.write("#") # for paragraph sapce
st.write("[Check the code here >](https://github.com/Football-1234/Large-Language-Models-LLMs-Generated-Text-Detection/tree/main)")
st.write("#")
st.markdown("<h2 style='color: #3366ff; font-weight: bold; text-align: center;'>The LLMs Detector is perfect for...</h2>", unsafe_allow_html=True)

# Dictionary containing the details for each category
checkbox_details = {
    "Student": {
        "Details": """<span style='font-family: "Times New Roman", Times, serif; color: #7ed0d0; font-weight: bold; font-size: 20px;'>Confidently submit your papers</span>

<span style='font-family: "Times New Roman", Times, serif;'>LLMs Detector helps ensure that your essays and papers adhere to your university guidelines.</span>

- <span style='font-family: "Times New Roman", Times, serif;'>Verify the authenticity of your sources ensuring that you only present trustworthy information.</span>

- <span style='font-family: "Times New Roman", Times, serif;'>Identify any AI-generated content, like ChatGPT, that might need proper attribution.</span>""",
        "Image": "https://www.scribbr.com/wp-content/uploads/2022/01/applicant.webp"
    },
    "Educator": {
        "Details": """<span style='font-family: "Times New Roman", Times, serif; color: #7ed0d0; font-weight: bold; font-size: 20px;'>Check the authenticity of your student's work</span>
        
<span style='font-family: "Times New Roman", Times, serif;'> More and more students are using AI tools, like ChatGPT in their writing process.</span>

- <span style='font-family: "Times New Roman", Times, serif;'> Analyze the content submitted by your students, ensuring that their work is actually written by them.</span>

- <span style='font-family: "Times New Roman", Times, serif;'> Promote a culture of honesty and originality among your students.</span>""",
        "Image": "https://www.scribbr.com/wp-content/uploads/2022/01/academic.webp"
    },
    "Blogger": {
        "Details": """<span style='font-family: "Times New Roman", Times, serif; color: #7ed0d0; font-weight: bold; font-size: 20px;'>Prevent search algorithm penalties</span>

<span style='font-family: "Times New Roman", Times, serif;'>Ensure that your content is indexed by publishing high-quality and original content.</span>

- <span style='font-family: "Times New Roman", Times, serif;'>Analyze the authenticity of articles written by external contributors or agencies before publishing them.</span>

- <span style='font-family: "Times New Roman", Times, serif;'> Deliver unique content that engages your audience and drives traffic to your website.</span>""",
        "Image": "https://www.scribbr.com/wp-content/uploads/2021/12/plagiatspruefung-betreuer-innen.jpg"
    }
}

selected_category = st.selectbox("Select a category", [''] + list(checkbox_details.keys()))
if selected_category:
    st.markdown(
        f"""
        <div style="display: flex; align-items: center;">
            <div style="flex: 1;">
                <h3>{selected_category}</h3>
                <p>{checkbox_details[selected_category]['Details']}</p>
            </div>
            <div style="flex: 1;">
                <img src="{checkbox_details[selected_category]['Image']}" alt="{selected_category} Image" width="200">
            </div>
        </div>
        """,
        unsafe_allow_html=True)
st.write("#")
st.write("#")

# Best AI detector data of 2024 (https://www.scribbr.com/ai-tools/best-ai-detector/)
data = {
    "Tool": ["Scribbr (premium)", "QuillBot", "Scribbr (free)", "Originality.AI", "Sapling", "CopyLeaks",
    "ZeroGPT", "GPT-2 Output Detector", "CrossPlag", "GPTZero", "Writer", "AI Text Classifier (OpenAI)"],
    "Accuracy": [84, 78, 78, 76, 68, 66, 64, 58, 58, 52, 38, 38],
    "False Positives": [0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1],
    "Star Rating": [4.2, 3.9, 3.9, 3.7, 3.4, 3.3, 3.1, 2.9, 2.9, 2.5, 1.9, 1.8]}
df = pd.DataFrame(data)

title_text = "Check Best AI Detectors of 2024"
st.title(title_text)

visualization_type = st.selectbox("Please select the type of data to visualize:", ("", "Accuracy", "False Positives", "Star Rating"))
if visualization_type:
    # Select data for visualization
    df_vis = df[["Tool", visualization_type]]

    # Create the bar chart using Altair
    chart = alt.Chart(df_vis).mark_bar().encode(
        x=alt.X('Tool', title='Tool'),
        y=alt.Y(visualization_type, title=visualization_type),
        tooltip=['Tool', visualization_type]).properties(width=600,height=400)

    st.altair_chart(chart, use_container_width=True)